package config

import (
	"fmt"
	"regexp"
	"strconv"

	"github.com/istoreos/quickstart/backend/models"
)

func ParseSmartConfig(conf string, running bool) *models.SmartConfigResponseResult {
	model := models.SmartConfigResponseResult{}
	global := models.SmartConfigGlobal{}
	global.Powermode = "standby"
	global.Enable = running
	model.Global = &global

	match := matchStringOnce(conf, `# smartd state (true|false)`)
	if match != nil {
		if match[1] == "true" {
			global.Enable = true
		} else if match[1] == "false" {
			global.Enable = false
		}
	}

	match = matchStringOnce(conf, `DEFAULT -n (\w+)`)
	if match != nil {
		global.Powermode = match[1]
	}

	deviceMatch := matchAllWithStr(conf, `(\/dev\/\w+) -W (\d+),\d+,(\d+)`)
	for _, v := range deviceMatch {
		device := models.SmartConfigDevice{}
		device.DevicePath = v[1]
		device.TmpDiff, _ = strconv.ParseInt(v[2], 10, 64)
		device.TmpMax, _ = strconv.ParseInt(v[3], 10, 64)
		model.Devices = append(model.Devices, &device)
	}

	taskMatch := matchAllWithStr(conf, `(\/dev\/\w+) -a -s (\w)\/([\d.]{2})\/([\d.]{2})\/([\d.])\/([\d.]{2})`)
	for _, v := range taskMatch {
		task := models.SmartConfigTask{}
		task.DevicePath = v[1]
		taskType := v[2]
		if taskType == "S" {
			task.Type = "short"
		} else if taskType == "L" {
			task.Type = "long"
		} else if taskType == "O" {
			task.Type = "offline"
		} else if taskType == "C" {
			task.Type = "conveyance"
		}

		task.Month = v[3]
		task.DayPerMonth = v[4]
		task.DayPerWeek = v[5]
		task.Hour = v[6]
		if v[3] == ".." {
			task.Month = "*"
		}
		if v[4] == ".." {
			task.DayPerMonth = "*"
		}
		if v[5] == "." {
			task.DayPerWeek = "*"
		}
		if v[6] == ".." {
			task.Hour = "*"
		}
		model.Tasks = append(model.Tasks, &task)
	}

	return &model
}

func RenderSmartdConfig(req *models.SmartConfigRequest) []string {
	lines := []string{
		"# Autogenerated, do not edit!",
		fmt.Sprintf("# smartd state %v", req.Global.Enable),
		fmt.Sprintf("DEFAULT -n %v", req.Global.Powermode),
	}

	for _, v := range req.Devices {
		if v.TmpDiff == 0 {
			v.TmpDiff = req.Global.TmpDiff
		}
		if v.TmpMax == 0 {
			v.TmpMax = req.Global.TmpMax
		}
		lines = append(lines, fmt.Sprintf("%v -W %v,0,%v", v.DevicePath, v.TmpDiff, v.TmpMax))
	}

	for _, v := range req.Tasks {
		taskType := "L"
		if v.Type == "long" {
			taskType = "L"
		} else if v.Type == "short" {
			taskType = "S"
		} else if v.Type == "offline" {
			taskType = "O"
		} else if v.Type == "conveyance" {
			taskType = "C"
		}

		month, _ := strconv.ParseInt(v.Month, 10, 64)
		monthStr := fmt.Sprintf("%02d", month)
		if v.Month == "*" {
			monthStr = ".."
		}
		dayPerMonth, _ := strconv.ParseInt(v.DayPerMonth, 10, 64)
		dayPerMonthStr := fmt.Sprintf("%02d", dayPerMonth)
		if v.DayPerMonth == "*" {
			dayPerMonthStr = ".."
		}
		hour, _ := strconv.ParseInt(v.Hour, 10, 64)
		hourStr := fmt.Sprintf("%02d", hour)
		if v.Hour == "*" {
			hourStr = ".."
		}
		dayPerWeekStr := v.DayPerWeek
		if v.DayPerWeek == "*" || len(dayPerWeekStr) == 0 {
			dayPerWeekStr = "."
		}
		lines = append(lines, fmt.Sprintf("%v -a -s %v/%v/%v/%v/%v", v.DevicePath, taskType, monthStr, dayPerMonthStr, dayPerWeekStr, hourStr))
	}

	return lines
}

func matchAllWithStr(str string, pattern string) [][]string {
	reg := regexp.MustCompile(pattern)
	return reg.FindAllStringSubmatch(str, -1)
}

func matchStringOnce(str string, pattern string) []string {
	reg := regexp.MustCompile(pattern)
	return reg.FindStringSubmatch(str)
}
