package config

import (
	"reflect"
	"testing"

	"github.com/istoreos/quickstart/backend/models"
)

func TestParseSmartConfig(t *testing.T) {
	conf := `# Autogenerated, do not edit!
# smartd state false
DEFAULT -n standby
/dev/sda -W 5,0,50
/dev/sda -a -s S/../03/./08
`

	got := ParseSmartConfig(conf, true)
	if got.Global == nil {
		t.Fatal("Global is nil")
	}
	if got.Global.Enable {
		t.Fatalf("Global.Enable = true, want false from smartd state")
	}
	if got.Global.Powermode != "standby" {
		t.Fatalf("Global.Powermode = %q, want standby", got.Global.Powermode)
	}
	if len(got.Devices) != 1 {
		t.Fatalf("len(Devices) = %d, want 1", len(got.Devices))
	}
	device := got.Devices[0]
	if device.DevicePath != "/dev/sda" || device.TmpDiff != 5 || device.TmpMax != 50 {
		t.Fatalf("device = %#v, want /dev/sda tmp diff 5 max 50", device)
	}
	if len(got.Tasks) != 1 {
		t.Fatalf("len(Tasks) = %d, want 1", len(got.Tasks))
	}
	task := got.Tasks[0]
	wantTask := &models.SmartConfigTask{
		DevicePath:  "/dev/sda",
		Type:        "short",
		Month:       "*",
		DayPerMonth: "03",
		DayPerWeek:  "*",
		Hour:        "08",
	}
	if !reflect.DeepEqual(task, wantTask) {
		t.Fatalf("task = %#v, want %#v", task, wantTask)
	}
}

func TestParseSmartConfigUsesRunningWhenStateMissing(t *testing.T) {
	got := ParseSmartConfig("DEFAULT -n sleep\n", true)
	if got.Global == nil {
		t.Fatal("Global is nil")
	}
	if !got.Global.Enable {
		t.Fatal("Global.Enable = false, want running state true")
	}
	if got.Global.Powermode != "sleep" {
		t.Fatalf("Global.Powermode = %q, want sleep", got.Global.Powermode)
	}
}

func TestRenderSmartdConfig(t *testing.T) {
	req := &models.SmartConfigRequest{
		Global: &models.SmartConfigGlobal{
			Enable:    true,
			Powermode: "standby",
			TmpDiff:   7,
			TmpMax:    55,
		},
		Devices: []*models.SmartConfigDevice{
			{DevicePath: "/dev/sda"},
		},
		Tasks: []*models.SmartConfigTask{
			{DevicePath: "/dev/sda", Type: "long", Month: "*", DayPerMonth: "*", DayPerWeek: "*", Hour: "*"},
			{DevicePath: "/dev/sdb", Type: "short", Month: "01", DayPerMonth: "02", DayPerWeek: "3", Hour: "04"},
			{DevicePath: "/dev/sdc", Type: "offline", Month: "05", DayPerMonth: "06", DayPerWeek: "", Hour: "07"},
			{DevicePath: "/dev/sdd", Type: "conveyance", Month: "08", DayPerMonth: "09", DayPerWeek: "1", Hour: "10"},
		},
	}

	got := RenderSmartdConfig(req)
	want := []string{
		"# Autogenerated, do not edit!",
		"# smartd state true",
		"DEFAULT -n standby",
		"/dev/sda -W 7,0,55",
		"/dev/sda -a -s L/../.././..",
		"/dev/sdb -a -s S/01/02/3/04",
		"/dev/sdc -a -s O/05/06/./07",
		"/dev/sdd -a -s C/08/09/1/10",
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("RenderSmartdConfig() = %#v, want %#v", got, want)
	}
}

func TestSmartConfigRoundTripKeepsKeyFields(t *testing.T) {
	req := &models.SmartConfigRequest{
		Global: &models.SmartConfigGlobal{
			Enable:    true,
			Powermode: "standby",
			TmpDiff:   5,
			TmpMax:    50,
		},
		Devices: []*models.SmartConfigDevice{
			{DevicePath: "/dev/sda", TmpDiff: 6, TmpMax: 60},
		},
		Tasks: []*models.SmartConfigTask{
			{DevicePath: "/dev/sda", Type: "short", Month: "*", DayPerMonth: "03", DayPerWeek: "*", Hour: "08"},
		},
	}

	lines := RenderSmartdConfig(req)
	parsed := ParseSmartConfig(joinSmartConfigLinesForTest(lines), false)

	if parsed.Global == nil || !parsed.Global.Enable || parsed.Global.Powermode != "standby" {
		t.Fatalf("parsed global = %#v, want enabled standby", parsed.Global)
	}
	if len(parsed.Devices) != 1 || parsed.Devices[0].DevicePath != "/dev/sda" || parsed.Devices[0].TmpDiff != 6 || parsed.Devices[0].TmpMax != 60 {
		t.Fatalf("parsed devices = %#v, want /dev/sda tmp diff 6 max 60", parsed.Devices)
	}
	if len(parsed.Tasks) != 1 || parsed.Tasks[0].DevicePath != "/dev/sda" || parsed.Tasks[0].Type != "short" || parsed.Tasks[0].Month != "*" || parsed.Tasks[0].DayPerMonth != "03" || parsed.Tasks[0].DayPerWeek != "*" || parsed.Tasks[0].Hour != "08" {
		t.Fatalf("parsed tasks = %#v, want short task preserving schedule", parsed.Tasks)
	}
}

func joinSmartConfigLinesForTest(lines []string) string {
	conf := ""
	for _, line := range lines {
		conf += line + "\n"
	}
	return conf
}
